const Form = require("../models/formModel")
const mongoose = require('mongoose')


// create new form
const createForm = async (req, res) => {

    //add form to db
    const {pFirstName,
         pLastName,
        homeNumber ,
        cellPhoneNumber ,
        email ,
        streetAddress ,
        city ,
        province ,
        postalCode ,
        childFirstName ,
        childLastName ,
        childID ,
        gender ,
        birthDate ,
        livesAtHome ,
        typeOfService ,
        albertaHealthCardNumber ,
        diagnoses ,
        eating ,
        dressing ,
        toileting ,
        activities ,
        speechAndHearing ,
        vision ,
        mobility ,
        specialInstructions ,
        primaryDoctor ,
        clinic ,
        clinicAddress ,
        clinicPhone ,
        emergencyTransport ,
        emergencyOption ,
        medications ,
        dosage ,
        numOfTimes ,
        prescribedFor ,
        medications2 ,
        dosage2 ,
        numOfTimes2 ,
        prescribedFor2 ,
        medications3 ,
        dosage3 ,
        numOfTimes3 ,
        prescribedFor3} = req.body
    try{
        const form = await Form.create({pFirstName,
            pLastName,
           homeNumber ,
           cellPhoneNumber ,
           email ,
           streetAddress ,
           city ,
           province ,
           postalCode ,
           childFirstName ,
           childLastName ,
           childID ,
           gender ,
           birthDate ,
           livesAtHome ,
           typeOfService ,
           albertaHealthCardNumber ,
           diagnoses ,
           eating ,
           dressing ,
           toileting ,
           activities ,
           speechAndHearing ,
           vision ,
           mobility ,
           specialInstructions ,
           primaryDoctor ,
           clinic ,
           clinicAddress ,
           clinicPhone ,
           emergencyTransport ,
           emergencyOption ,
           medications ,
           dosage ,
           numOfTimes ,
           prescribedFor ,
           medications2 ,
           dosage2 ,
           numOfTimes2 ,
           prescribedFor2 ,
           medications3 ,
           dosage3 ,
           numOfTimes3 ,
           prescribedFor3})
        res.status(200).json(form)
    } catch(error){
        res.status(400).json({error: error.message})
    }
}

module.exports = { createForm }