const mongoose = require("mongoose");

const formsSchema = {
  pFirstName: String,
  pLastName: String,
  homeNumber: String,
  cellPhoneNumber: String,
  email: String,
  streetAddress: String,
  city: String,
  province: String,
  postalCode: String,
  childFirstName: String,
  childLastName: String,
  childID: String,
  gender: String,
  birthDate: String,
  livesAtHome: String,
  typeOfService: String,
  albertaHealthCardNumber: String,
  diagnoses: String,
  eating: String,
  dressing: String,
  toileting: String,
  activities: String,
  speechAndHearing: String,
  vision: String,
  mobility: String,
  specialInstructions: String,
  primaryDoctor: String,
  clinic: String,
  clinicAddress: String,
  clinicPhone: String,
  emergencyTransport: String,
  emergencyOption: String,
  medications: String,
  dosage: String,
  numOfTimes: String,
  prescribedFor: String,
  medications2: String,
  dosage2: String,
  numOfTimes2: String,
  prescribedFor2: String,
  medications3: String,
  dosage3: String,
  numOfTimes3: String,
  prescribedFor3: String,
};

const Form = mongoose.model("Form", formsSchema);

module.exports = Form;
